version: "3.8"

services:
  app:
    container_name: hacker-news-clone
    image: hacker-news-clone
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000